version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    env_file:
        - .env
    ports:
      - "${DB_PORT}"
    container_name: picassodb
    volumes:
      - ./postgres:/var/lib/postgresql/data